version: "2"
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3200:3200"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://foodapp@postgres/foodapp
  postgres:
    image: kartoza/postgis:12.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: foodapp
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: foodapp
