

const countries = [
    { label: 'Afghanistan' }, { label: 'Albania' }, { label: 'Algeria' }, { label: 'American Samoa' },
    { label: 'Andorra' }, { label: 'Angola' }, { label: 'Anguilla' }, { label: 'Antarctica' },
    { label: 'Antigua and Barbuda' }, { label: 'Argentina' }, { label: 'Armenia' }, { label: 'Aruba' },
    { label: 'Australia' }, { label: 'Austria' }, { label: 'Azerbaijan' }, { label: 'Bahamas' },
    { label: 'Bahrain' }, { label: 'Bangladesh' }, { label: 'Barbados' }, { label: 'Belarus' },
    { label: 'Belgium' }, { label: 'Belize' }, { label: 'Benin' }, { label: 'Bermuda' },
    { label: 'Bhutan' }, { label: 'Bolivia' }, { label: 'Bosnia and Herzegovina' }, { label: 'Botswana' },
    { label: 'Brazil' }, { label: 'British Indian Ocean Territory' }, { label: 'British Virgin Islands' }, { label: 'Brunei' },
    { label: 'Bulgaria' }, { label: 'Burkina Faso' }, { label: 'Burundi' }, { label: 'Cambodia' },
    { label: 'Cameroon' }, { label: 'Canada' }, { label: 'Cape Verde' }, { label: 'Cayman Islands' },
    { label: 'Central African Republic' }, { label: 'Chad' }, { label: 'Chile' }, { label: 'China' },
    { label: 'Christmas Island' }, { label: 'Cocos Islands' }, { label: 'Colombia' }, { label: 'Comoros' },
    { label: 'Cook Islands' }, { label: 'Costa Rica' }, { label: 'Croatia' }, { label: 'Cuba' },
    { label: 'Curacao' }, { label: 'Cyprus' }, { label: 'Czech Republic' }, { label: 'Democratic Republic of the Congo' },
    { label: 'Denmark' }, { label: 'Djibouti' }, { label: 'Dominica' }, { label: 'Dominican Republic' },
    { label: 'East Timor' }, { label: 'Ecuador' }, { label: 'Egypt' }, { label: 'El Salvador' },
    { label: 'Equatorial Guinea' }, { label: 'Eritrea' }, { label: 'Estonia' }, { label: 'Ethiopia' },
    { label: 'Falkland Islands' }, { label: 'Faroe Islands' }, { label: 'Fiji' }, { label: 'Finland' },
    { label: 'France' }, { label: 'French Polynesia' }, { label: 'Gabon' }, { label: 'Gambia' },
    { label: 'Georgia' }, { label: 'Germany' }, { label: 'Ghana' }, { label: 'Gibraltar' },
    { label: 'Greece' }, { label: 'Greenland' }, { label: 'Grenada' }, { label: 'Guam' },
    { label: 'Guatemala' }, { label: 'Guernsey' }, { label: 'Guinea' }, { label: 'Guinea-Bissau' },
    { label: 'Guyana' }, { label: 'Haiti' }, { label: 'Honduras' }, { label: 'Hong Kong' },
    { label: 'Hungary' }, { label: 'Iceland' }, { label: 'India' }, { label: 'Indonesia' },
    { label: 'Iran' }, { label: 'Iraq' }, { label: 'Ireland' }, { label: 'Isle of Man' },
    { label: 'Israel' }, { label: 'Italy' }, { label: 'Ivory Coast' }, { label: 'Jamaica' },
    { label: 'Japan' }, { label: 'Jersey' }, { label: 'Jordan' }, { label: 'Kazakhstan' },
    { label: 'Kenya' }, { label: 'Kiribati' }, { label: 'Kosovo' }, { label: 'Kuwait' },
    { label: 'Kyrgyzstan' }, { label: 'Laos' }, { label: 'Latvia' }, { label: 'Lebanon' },
    { label: 'Lesotho' }, { label: 'Liberia' }, { label: 'Libya' }, { label: 'Liechtenstein' },
    { label: 'Lithuania' }, { label: 'Luxembourg' }, { label: 'Macau' }, { label: 'Macedonia' },
    { label: 'Madagascar' }, { label: 'Malawi' }, { label: 'Malaysia' }, { label: 'Maldives' },
    { label: 'Mali' }, { label: 'Malta' }, { label: 'Marshall Islands' }, { label: 'Mauritania' },
    { label: 'Mauritius' }, { label: 'Mayotte' }, { label: 'Mexico' }, { label: 'Micronesia' },
    { label: 'Moldova' }, { label: 'Monaco' }, { label: 'Mongolia' }, { label: 'Montenegro' },
    { label: 'Montserrat' }, { label: 'Morocco' }, { label: 'Mozambique' }, { label: 'Myanmar' },
    { label: 'Namibia' }, { label: 'Nauru' }, { label: 'Nepal' }, { label: 'Netherlands' },
    { label: 'Netherlands Antilles' }, { label: 'New Caledonia' }, { label: 'New Zealand' }, { label: 'Nicaragua' },
    { label: 'Niger' }, { label: 'Nigeria' }, { label: 'Niue' }, { label: 'North Korea' },
    { label: 'Northern Mariana Islands' }, { label: 'Norway' }, { label: 'Oman' }, { label: 'Pakistan' },
    { label: 'Palau' }, { label: 'Palestine' }, { label: 'Panama' }, { label: 'Papua New Guinea' },
    { label: 'Paraguay' }, { label: 'Peru' }, { label: 'Philippines' }, { label: 'Pitcairn' },
    { label: 'Poland' }, { label: 'Portugal' }, { label: 'Puerto Rico' }, { label: 'Qatar' },
    { label: 'Republic of the Congo' }, { label: 'Reunion' }, { label: 'Romania' }, { label: 'Russia' },
    { label: 'Rwanda' }, { label: 'Saint Barthelemy' }, { label: 'Saint Helena' }, { label: 'Saint Kitts and Nevis' },
    { label: 'Saint Lucia' }, { label: 'Saint Martin' }, { label: 'Saint Pierre and Miquelon' }, { label: 'Saint Vincent and the Grenadines' },
    { label: 'Samoa' }, { label: 'San Marino' }, { label: 'Sao Tome and Principe' }, { label: 'Saudi Arabia' },
    { label: 'Senegal' }, { label: 'Serbia' }, { label: 'Seychelles' }, { label: 'Sierra Leone' },
    { label: 'Singapore' }, { label: 'Sint Maarten' }, { label: 'Slovakia' }, { label: 'Slovenia' },
    { label: 'Solomon Islands' }, { label: 'Somalia' }, { label: 'South Africa' }, { label: 'South Korea' },
    { label: 'South Sudan' }, { label: 'Spain' }, { label: 'Sri Lanka' }, { label: 'Sudan' },
    { label: 'Suriname' }, { label: 'Svalbard and Jan Mayen' }, { label: 'Swaziland' }, { label: 'Sweden' },
    { label: 'Switzerland' }, { label: 'Syria' }, { label: 'Taiwan' }, { label: 'Tajikistan' },
    { label: 'Tanzania' }, { label: 'Thailand' }, { label: 'Togo' }, { label: 'Tokelau' },
    { label: 'Tonga' }, { label: 'Trinidad and Tobago' }, { label: 'Tunisia' }, { label: 'Turkey' },
    { label: 'Turkmenistan' }, { label: 'Turks and Caicos Islands' }, { label: 'Tuvalu' }, { label: 'U.S. Virgin Islands' },
    { label: 'Uganda' }, { label: 'Ukraine' }, { label: 'United Arab Emirates' }, { label: 'United Kingdom' },
    { label: 'United States' }, { label: 'Uruguay' }, { label: 'Uzbekistan' }, { label: 'Vanuatu' },
    { label: 'Vatican' }, { label: 'Venezuela' }, { label: 'Vietnam' }, { label: 'Wallis and Futuna' },
    { label: 'Western Sahara' }, { label: 'Yemen' }, { label: 'Zambia' }, { label: 'Zimbabwe' }
];
const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']


const countriesCode = [
    { label: '93 (AFG)', value: '93' }, { label: '355 (ALB)', value: '355' }, { label: '213 (DZA)', value: '213' }, { label: '1-684 (ASM)', value: '1-684' },
    { label: '376 (AND)', value: '376' }, { label: '244 (AGO)', value: '244' }, { label: '1-264 (AIA)', value: '1-264' }, { label: '672 (ATA)', value: '672' },
    { label: '1-268 (ATG)', value: '1-268' }, { label: '54 (ARG)', value: '54' }, { label: '374 (ARM)', value: '374' }, { label: '297 (ABW)', value: '297' },
    { label: '61 (AUS)', value: '61' }, { label: '43 (AUT)', value: '43' }, { label: '994 (AZE)', value: '994' }, { label: '1-242 (BHS)', value: '1-242' },
    { label: '973 (BHR)', value: '973' }, { label: '880 (BGD)', value: '880' }, { label: '1-246 (BRB)', value: '1-246' }, { label: '375 (BLR)', value: '375' },
    { label: '32 (BEL)', value: '32' }, { label: '501 (BLZ)', value: '501' }, { label: '229 (BEN)', value: '229' }, { label: '1-441 (BMU)', value: '1-441' },
    { label: '975 (BTN)', value: '975' }, { label: '591 (BOL)', value: '591' }, { label: '387 (BIH)', value: '387' }, { label: '267 (BWA)', value: '267' },
    { label: '55 (BRA)', value: '55' }, { label: '246 (IOT)', value: '246' }, { label: '1-284 (VGB)', value: '1-284' }, { label: '673 (BRN)', value: '673' },
    { label: '359 (BGR)', value: '359' }, { label: '226 (BFA)', value: '226' }, { label: '257 (BDI)', value: '257' }, { label: '855 (KHM)', value: '855' },
    { label: '237 (CMR)', value: '237' }, { label: '238 (CPV)', value: '238' }, { label: '1-345 (CYM)', value: '1-345' },
    { label: '236 (CAF)', value: '236' }, { label: '235 (TCD)', value: '235' }, { label: '56 (CHL)', value: '56' }, { label: '86 (CHN)', value: '86' },
    { label: '61 (CXR)', value: '61' }, { label: '61 (CCK)', value: '61' }, { label: '57 (COL)', value: '57' }, { label: '269 (COM)', value: '269' },
    { label: '682 (COK)', value: '682' }, { label: '506 (CRI)', value: '506' }, { label: '385 (HRV)', value: '385' }, { label: '53 (CUB)', value: '53' },
    { label: '599 (CUW)', value: '599' }, { label: '357 (CYP)', value: '357' }, { label: '420 (CZE)', value: '420' }, { label: '243 (COD)', value: '243' },
    { label: '45 (DNK)', value: '45' }, { label: '253 (DJI)', value: '253' }, { label: '1-767 (DMA)', value: '1-767' },
    { label: '1-809 (DOM)', value: '1-809' }, { label: '1-829 (DOM)', value: '1-829' }, { label: '1-849 (DOM)', value: '1-849' },
    { label: '670 (TLS)', value: '670' }, { label: '593 (ECU)', value: '593' }, { label: '20 (EGY)', value: '20' }, { label: '503 (SLV)', value: '503' },
    { label: '240 (GNQ)', value: '240' }, { label: '291 (ERI)', value: '291' }, { label: '372 (EST)', value: '372' }, { label: '251 (ETH)', value: '251' },
    { label: '500 (FLK)', value: '500' }, { label: '298 (FRO)', value: '298' }, { label: '679 (FJI)', value: '679' }, { label: '358 (FIN)', value: '358' },
    { label: '33 (FRA)', value: '33' }, { label: '689 (PYF)', value: '689' }, { label: '241 (GAB)', value: '241' }, { label: '220 (GMB)', value: '220' },
    { label: '995 (GEO)', value: '995' }, { label: '49 (DEU)', value: '49' }, { label: '233 (GHA)', value: '233' }, { label: '350 (GIB)', value: '350' },
    { label: '30 (GRC)', value: '30' }, { label: '299 (GRL)', value: '299' }, { label: '1-473 (GRD)', value: '1-473' }, { label: '1-671 (GUM)', value: '1-671' },
    { label: '502 (GTM)', value: '502' }, { label: '44-1481 (GGY)', value: '44-1481' }, { label: '224 (GIN)', value: '224' }, { label: '245 (GNB)', value: '245' },
    { label: '592 (GUY)', value: '592' }, { label: '509 (HTI)', value: '509' }, { label: '504 (HND)', value: '504' }, { label: '852 (HKG)', value: '852' },
    { label: '36 (HUN)', value: '36' }, { label: '354 (ISL)', value: '354' }, { label: '91 (IND)', value: '91' }, { label: '62 (IDN)', value: '62' },
    { label: '98 (IRN)', value: '98' }, { label: '964 (IRQ)', value: '964' }, { label: '353 (IRL)', value: '353' }, { label: '44-1624 (IMN)', value: '44-1624' },
    { label: '972 (ISR)', value: '972' }, { label: '39 (ITA)', value: '39' }, { label: '225 (CIV)', value: '225' }, { label: '1-876 (JAM)', value: '1-876' },
    { label: '81 (JPN)', value: '81' }, { label: '44-1534 (JEY)', value: '44-1534' }, { label: '962 (JOR)', value: '962' }, { label: '7 (KAZ)', value: '7' },
    { label: '254 (KEN)', value: '254' }, { label: '686 (KIR)', value: '686' }, { label: '383 (XKX)', value: '383' }, { label: '965 (KWT)', value: '965' },
    { label: '996 (KGZ)', value: '996' }, { label: '856 (LAO)', value: '856' }, { label: '371 (LVA)', value: '371' }, { label: '961 (LBN)', value: '961' },
    { label: '266 (LSO)', value: '266' }, { label: '231 (LBR)', value: '231' }, { label: '218 (LBY)', value: '218' }, { label: '423 (LIE)', value: '423' },
    { label: '370 (LTU)', value: '370' }, { label: '352 (LUX)', value: '352' }, { label: '853 (MAC)', value: '853' }, { label: '389 (MKD)', value: '389' },
    { label: '261 (MDG)', value: '261' }, { label: '265 (MWI)', value: '265' }, { label: '60 (MYS)', value: '60' }, { label: '960 (MDV)', value: '960' },
    { label: '223 (MLI)', value: '223' }, { label: '356 (MLT)', value: '356' }, { label: '692 (MHL)', value: '692' }, { label: '222 (MRT)', value: '222' },
    { label: '230 (MUS)', value: '230' }, { label: '262 (MYT)', value: '262' }, { label: '52 (MEX)', value: '52' }, { label: '691 (FSM)', value: '691' },
    { label: '373 (MDA)', value: '373' }, { label: '377 (MCO)', value: '377' }, { label: '976 (MNG)', value: '976' }, { label: '382 (MNE)', value: '382' },
    { label: '1-664 (MSR)', value: '1-664' }, { label: '212 (MAR)', value: '212' }, { label: '258 (MOZ)', value: '258' }, { label: '95 (MMR)', value: '95' },
    { label: '264 (NAM)', value: '264' }, { label: '674 (NRU)', value: '674' }, { label: '977 (NPL)', value: '977' }, { label: '31 (NLD)', value: '31' },
    { label: '599 (ANT)', value: '599' }, { label: '687 (NCL)', value: '687' }, { label: '64 (NZL)', value: '64' }, { label: '505 (NIC)', value: '505' },
    { label: '227 (NER)', value: '227' }, { label: '234 (NGA)', value: '234' }, { label: '683 (NIU)', value: '683' }, { label: '850 (PRK)', value: '850' },
    { label: '1-670 (MNP)', value: '1-670' }, { label: '47 (NOR)', value: '47' }, { label: '968 (OMN)', value: '968' }, { label: '92 (PAK)', value: '92' },
    { label: '680 (PLW)', value: '680' }, { label: '970 (PSE)', value: '970' }, { label: '507 (PAN)', value: '507' }, { label: '675 (PNG)', value: '675' },
    { label: '595 (PRY)', value: '595' }, { label: '51 (PER)', value: '51' }, { label: '63 (PHL)', value: '63' }, { label: '64 (PCN)', value: '64' },
    { label: '48 (POL)', value: '48' }, { label: '351 (PRT)', value: '351' }, { label: '1-787, 1-939 (PRI)', value: '1-787, 1-939' }, { label: '974 (QAT)', value: '974' },
    { label: '242 (COG)', value: '242' }, { label: '262 (REU)', value: '262' }, { label: '40 (ROU)', value: '40' }, { label: '7 (RUS)', value: '7' },
    { label: '250 (RWA)', value: '250' }, { label: '590 (BLM)', value: '590' }, { label: '290 (SHN)', value: '290' }, { label: '1-869 (KNA)', value: '1-869' },
    { label: '1-758 (LCA)', value: '1-758' }, { label: '590 (MAF)', value: '590' }, { label: '508 (SPM)', value: '508' }, { label: '1-784 (VCT)', value: '1-784' },
    { label: '685 (WSM)', value: '685' }, { label: '378 (SMR)', value: '378' }, { label: '239 (STP)', value: '239' }, { label: '966 (SAU)', value: '966' },
    { label: '221 (SEN)', value: '221' }, { label: '381 (SRB)', value: '381' }, { label: '248 (SYC)', value: '248' }, { label: '232 (SLE)', value: '232' },
    { label: '65 (SGP)', value: '65' }, { label: '1-721 (SXM)', value: '1-721' }, { label: '421 (SVK)', value: '421' }, { label: '386 (SVN)', value: '386' },
    { label: '677 (SLB)', value: '677' }, { label: '252 (SOM)', value: '252' }, { label: '27 (ZAF)', value: '27' }, { label: '82 (KOR)', value: '82' },
    { label: '211 (SSD)', value: '211' }, { label: '34 (ESP)', value: '34' }, { label: '94 (LKA)', value: '94' }, { label: '249 (SDN)', value: '249' },
    { label: '597 (SUR)', value: '597' }, { label: '47 (SJM)', value: '47' }, { label: '268 (SWZ)', value: '268' }, { label: '46 (SWE)', value: '46' },
    { label: '41 (CHE)', value: '41' }, { label: '963 (SYR)', value: '963' }, { label: '886 (TWN)', value: '886' }, { label: '992 (TJK)', value: '992' },
    { label: '255 (TZA)', value: '255' }, { label: '66 (THA)', value: '66' }, { label: '228 (TGO)', value: '228' }, { label: '690 (TKL)', value: '690' },
    { label: '676 (TON)', value: '676' }, { label: '1-868 (TTO)', value: '1-868' }, { label: '216 (TUN)', value: '216' }, { label: '90 (TUR)', value: '90' },
    { label: '993 (TKM)', value: '993' }, { label: '1-649 (TCA)', value: '1-649' }, { label: '688 (TUV)', value: '688' }, { label: '1-340 (VIR)', value: '1-340' },
    { label: '256 (UGA)', value: '256' }, { label: '380 (UKR)', value: '380' }, { label: '971 (ARE)', value: '971' }, { label: '44 (GBR)', value: '44' },
    { label: '1 (USA/CAN)', value: '1' }, { label: '598 (URY)', value: '598' }, { label: '998 (UZB)', value: '998' }, { label: '678 (VUT)', value: '678' },
    { label: '379 (VAT)', value: '379' }, { label: '58 (VEN)', value: '58' }, { label: '84 (VNM)', value: '84' }, { label: '681 (WLF)', value: '681' },
    { label: '212 (ESH)', value: '212' }, { label: '967 (YEM)', value: '967' }, { label: '260 (ZMB)', value: '260' }, { label: '263 (ZWE)', value: '263' }
];


export {
    countries, 
    months,
    countriesCode,
   
}


